services:
  nginx-proxy:
    build: .
    container_name: nginx-proxy
    ports:
      - "8080:80"
    restart: unless-stopped
    network_mode: bridge
    external_links:
      - flask-container
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
